clientes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

app_name = 'clientes'


router = DefaultRouter()
router.register(r'clientes-api', ClienteViewSet)
router.register(r'visitas', VisitaViewSet, basename='visitas')
router.register(r'llamadas', LlamadaViewSet)

crm_django/urls.py
from django.urls import include, path, re_path
from clientes.views import * 
from authentication.views import *
from clientes.urls import router as clientes_router 


urlpatterns = [
    path('', include(clientes_router.urls)),
    re_path('login-api', login),
    re_path('signup-api', signup),
]

fachadas/urls.py
from django.urls import include, path
from fachadas.views import *
app_name="fachadas"


urlpatterns = [
    path('', ObraListView.as_view(), name="lista-obra"),
    path("iniciar-obra/", ObraCreateView.as_view(), name="iniciar-obra"),
    path("<int:obra_pk>/<str:año_mes>/<str:dia>", ObraDetailView.as_view(), name="detalles-obra"),
    path("eliminar-obra/<int:pk>", ObraDeleteView.as_view(), name="eliminar-obra"),
    path("<int:pk>/<str:año_mes>/<str:dia>/añadir-costo/", CostoCreateView.as_view(), name="crear-costo"),
    path("<int:pk>/<str:año_mes>/<str:dia>/añadir-trabajador", TrabajadorCreateView.as_view(), name="crear-trabajador"),
    path("<int:pk>/<str:año_mes>/<str:dia>/pagar_nomina", pagar_nomina, name="pagar-nomina"),
    path("<int:obra_pk>/<str:inicio_pago>/<str:final_pago>/pagos/", PagoListView.as_view(), name="filtrar-pagos"),
    path("<int:obra_pk>/<str:inicio_pago>/<str:final_pago>/eliminar-pago/<int:pk>/", PagoDeleteView.as_view(), name="eliminar-pago"),
#    path("<int:obra_pk>/<str:año_mes>/<str:dia>/subir-archivo", subir_archivo, name="subir-archivo"),

    ]

general_usage/urls.py
from django.urls import include, path
from general_usage.views import *
app_name="general_usage"


urlpatterns=[
        path("crear_nota/<str:tipo>/<int:pk>/", NotaCreateView.as_view(), name="crear-nota"),
        path("subir_archivo/<str:tipo>/<int:pk>/", ArchivoCreateView.as_view(), name="subir-archivo"),
        path("crear-pedido/<str:tipo>/<str:fecha>/<int:pk>/", PedidoFormsetView.as_view(), name="crear-pedido"),
        path('ajax/cargar_subelementos', cargar_subelementos, name='ajax_cargar_subelementos'), # AJAX
        path("detalles_pedido/<int:pedido_pk>/", PedidoDetailView.as_view(), name="detalles-pedido"),
        path("lista-objetos/<str:tipo>/<str:fecha>/<int:pk>/", ObjetoListView.as_view(), name="lista-objetos"),
        ]

fachadas/models.py
from datetime import date
from django.db import models

class Obra(models.Model):

    CHOICES_ESTADO = (("EN PROCESO", "En proceso"), ("FINALIZADA", "Finalizada"))

    nombre_obra = models.CharField(max_length=30)
    direccion = models.CharField(max_length=30)
    nit = models.IntegerField()
    administrador = models.CharField(max_length=30)
    numero_tel = models.IntegerField()
    correo = models.EmailField(null=True)
    empleado = models.ForeignKey("clientes.Empleado", on_delete=models.SET_NULL, null=True)
    estado = models.CharField(max_length=10, choices = CHOICES_ESTADO)
    fecha_inicio = models.DateField(null=False, default=date.today)
    costo_total = models.FloatField(default=0)
    fecha_ultimo_pago = models.CharField(max_length=25, default=0)

    def __str__(self):
        return f"{self.nombre_obra}"


class Costo(models.Model):
    descripcion = models.CharField(max_length=30)
    cantidad = models.IntegerField()
    fecha = models.DateField(null=False, default=date.today)
    obra = models.ForeignKey("fachadas.Obra", on_delete=models.CASCADE)
    precio_unidad = models.FloatField()
    cobro_unidad = models.FloatField()

    def __str__(self):
        return f"{self.descripcion}"

class Accion(Costo):
    trabajador = models.ForeignKey("fachadas.Trabajador", on_delete=models.SET_NULL, null=True)

class Trabajador(models.Model):
    CHOICES_TIPO = (("SUPERVISOR", "Supervisor"), ("OBRERO", "Obrero"))
    nombre = models.CharField(max_length=30)
    cargo = models.CharField(max_length=30,choices = CHOICES_TIPO)
    obra = models.ForeignKey("fachadas.Obra", on_delete=models.SET_NULL, null=True)
    acumulado = models.FloatField(default=0)
    
    def __str__(self):
        return f"{self.nombre}"

class Pago(models.Model):
    fecha = models.DateField(null=False)
    periodo_inicio = models.DateField()
    periodo_final = models.DateField()
    monto = models.FloatField()
    trabajador = models.ForeignKey("fachadas.Trabajador", on_delete=models.CASCADE, null=False)
    obra = models.ForeignKey("fachadas.Obra", on_delete=models.CASCADE, null=False)
    def __str__(self):
        return f"{self.monto}"

fachadas/forms.py
from datetime import datetime
from django import forms


from fachadas.models import *

class ObraModelForm(forms.ModelForm):
    class Meta:
        model = Obra
        fields = ("nombre_obra",
                  "direccion",
                  "nit",
                  "administrador",
                  "correo",
                  "numero_tel",
                  "estado",
                  )
        widgets = {
                "nombre_obra" : forms.TextInput(attrs={"class": "form-control"}),
                "direccion" : forms.TextInput(attrs={"class": "form-control"}),
                "nit" : forms.NumberInput(attrs={"class":"form-control"}),
                "administrador": forms.TextInput(attrs={"class":"form-control"}),
                "correo" : forms.EmailInput(attrs={"class":"form-control"}),
                "estado" : forms.Select(attrs={"class":"form-control"}),
                "numero_tel":forms.NumberInput(attrs={"class":"form-control"})
                }

class CostoForm(forms.Form):
    dict = {"class":"form-control"}
    modelos = (("COSTO", "Costo"), ("ACCION", "Accion"))
    tipo = forms.ChoiceField(widget=forms.Select(attrs={"class":"form-control", "onchange":"select_form()"}), choices=modelos)
    descripcion = forms.CharField(widget = forms.TextInput(attrs=dict))
    cantidad = forms.IntegerField(widget = forms.NumberInput(attrs=dict))
    precio_unidad = forms.FloatField(widget=forms.NumberInput(attrs=dict)) 
    cobro_unidad = forms.FloatField(widget=forms.NumberInput(attrs=dict))

    def __init__(self, *args, **kwargs):
        obra = kwargs.pop("obra",0)
        trabajadores =  Trabajador.objects.filter(obra=obra)
        super(CostoForm, self).__init__( *args, **kwargs)
        dict_fecha = self.dict
        dict_fecha.update({"type": "date", "min": obra.fecha_inicio.strftime("%Y-%m-%d"), "max": date.today()})
        self.fields["fecha"] = forms.DateField(widget=forms.DateInput(attrs=dict_fecha))

        self.fields["trabajador"] = forms.ModelChoiceField(queryset=trabajadores, label="", empty_label="Seleccione el trabajador", widget=forms.Select(attrs={"class":"form-control", "style": "display:none;"}))
        self.fields["trabajador"].required = False

class TrabajadorModelForm(forms.ModelForm):
    class Meta:
        model = Trabajador
        fields = ("nombre",
                  "cargo")
        widgets = {
                "nombre" : forms.TextInput(attrs={"class":"form-control"}),
                "cargo" : forms.Select(attrs={"class": "form-control"})
                }

fachadas/views.py
from datetime import datetime
import os
from shutil import rmtree
from django.http import response
from django.shortcuts import redirect, render, reverse
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, TemplateView
from clientes.models import Empleado
from fachadas.models import *
from fachadas.forms import *
from fachadas.functions import *
from fachadas.mixins import EmpleadoRequiredMixin
from functions import create_folder, write_file
# Create your views here.

CARPETA_FACHADAS = "/home/anorak/Test/Fachadas/"

class ObraListView(EmpleadoRequiredMixin, ListView):
    template_name = "fachadas/lista_fachadas.html"

    def get_queryset(self):
        return Obra.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ObraListView, self).get_context_data(**kwargs)
        obras = Obra.objects.all()
        urls = [reverse("fachadas:eliminar-obra", args=[i.id]) for i in obras]
        obras = zip(obras, urls)
        fecha = date.today()
        context.update({
            "año_mes": fecha.strftime("%Y-%m"),
            "dia":fecha.strftime("%d"),
            "obras": obras
            })
        return context

class ObraCreateView(EmpleadoRequiredMixin, CreateView):
    template_name ="fachadas/iniciar_obra.html"
    form_class = ObraModelForm

    def get_success_url(self):
        return reverse("fachadas:lista-obra")

    def get_context_data(self, **kwargs):
        context = super(ObraCreateView, self).get_context_data(**kwargs)
        context.update({
            "previous":reverse("fachadas:lista-obra")

            })
        return context 

    def form_valid(self, form):
        form.instance.empelado = Empleado.objects.get(user=self.request.user)
        create_folder(CARPETA_FACHADAS + form.instance.nombre_obra)
        return super(ObraCreateView, self).form_valid(form)

class ObraDetailView(EmpleadoRequiredMixin, DetailView):
    template_name = "fachadas/detalles_obra.html"
    pk_url_kwarg = "obra_pk"
    queryset = Obra.objects.all()

    def get_success_url(self):
        return reverse("fachadas:detalles-obra", args=[self.kwargs["obra_pk"]])

    def get(self, request, *args, **kwargs):
        if kwargs["dia"] == "32":
            obra = self.get_object()
            dict_fecha = unir_fecha(kwargs) 
            costos_dict = costos_mes(dict_fecha, obra)
            dia_maximo = costos_dict["dias_mes"][0]
            return redirect("fachadas:detalles-obra", self.kwargs["obra_pk"], self.kwargs["año_mes"], dia_maximo)
        return super(ObraDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ObraDetailView, self).get_context_data(**kwargs)
        obra = self.get_object()
        trabajadores = Trabajador.objects.filter(obra = obra)
        pagos =[]
        try:
            pagos = Pago.objects.filter(obra=obra)
            pagos = [pagos.filter(trabajador=i).order_by("-fecha").first() for i in trabajadores] 
        except:
            pass
        trabajadores_pagos = zip(trabajadores, pagos)

        dict_fecha = unir_fecha(self.kwargs)
        costos_dict = costos_mes(dict_fecha, obra)
        costos_display = costos_dict["costos"].filter(fecha=dict_fecha["fecha"]) 
        meses_unicos = [i["fecha"].strftime("%Y-%m") for i in costos_dict["costos"].values("fecha").annotate(n = models.Count("pk"))]
        meses_unicos = valores_unicos(meses_unicos)

        try:
            meses_unicos.remove(dict_fecha["año_mes"])
        except:
            pass

        meses_unicos.insert(0, dict_fecha["año_mes"])
        #expenses to be disaplayed on the web page
        costos_display = asignar_acciones(costos_display, obra, dict_fecha["fecha"])

        context.update({
            "previous":reverse("fachadas:lista-obra"),
            "obra":obra,
            "trabajadores": trabajadores,
            "costos":costos_display,
            "dias":costos_dict["dias_mes"],
            "dict_fecha":dict_fecha,
            "meses_unicos":meses_unicos,
            "trabajadores_pagos":trabajadores_pagos
            })
        return context

class ObraDeleteView(EmpleadoRequiredMixin, DeleteView):
    model = Obra
    http_method_names = ['delete']

    def dispatch(self, request, *args, **kwargs):
        instance = Obra.objects.get(id=self.kwargs["pk"])
        rmtree(CARPETA_FACHADAS + instance.nombre_obra)
        handler = getattr(self, 'delete')
        return handler(request, *args, **kwargs)

    def get_success_url(self):
        success_url = str(reverse('fachadas:lista-obra'))
        return success_url

def pagar_nomina(request, pk, año_mes, dia):
    obra = Obra.objects.get(id=pk)
    trabajadores = Trabajador.objects.filter(obra=obra)
    if request.method == "POST":
        inicio_nomina = request.POST["inicio_nomina"] 
        final_nomina = request.POST["final_nomina"]
        for trabajador in trabajadores:
            acciones = Accion.objects.filter(trabajador=trabajador, 
                                             fecha__gte=inicio_nomina, 
                                             fecha__lte=final_nomina)
            valor_nomina = sum([i.precio_unidad * i.cantidad for i in acciones])
            trabajador.acumulado -= valor_nomina
            if trabajador.acumulado < 0:
                trabajador.acumulado = 0
            obra.fecha_ultimo_pago = date.today() 
            Pago.objects.create(fecha=date.today(), 
                                monto=valor_nomina, 
                                periodo_inicio=inicio_nomina, 
                                periodo_final=final_nomina, 
                                trabajador=trabajador, 
                                obra=obra)
            trabajador.save()
            obra.save()

    return redirect(reverse("fachadas:detalles-obra", args=[pk, año_mes, dia]))

class CostoCreateView(EmpleadoRequiredMixin, FormView):
    template_name = "fachadas/crear_costo.html"
    form_class=CostoForm

    def get_success_url(self):
        dict = unir_fecha(self.kwargs)
        return reverse("fachadas:detalles-obra", args=[self.kwargs["pk"], dict["año_mes"], dict["dia"]])

    def get_form_kwargs(self):
        #pass kwarg with last visit
        kwargs = super().get_form_kwargs()
        kwargs["obra"] = Obra.objects.get(id=self.kwargs["pk"])
        return kwargs

    def get_context_data(self, **kwargs):
        dict = unir_fecha(self.kwargs)
        context = super(CostoCreateView, self).get_context_data(**kwargs)
        context.update({
            "previous":reverse("fachadas:detalles-obra", args=[self.kwargs["pk"], dict["año_mes"], dict["dia"]])
            })
        return context

    def form_valid(self, form):
        descripcion = form.cleaned_data["descripcion"]
        cantidad = form.cleaned_data["cantidad"]
        fecha = form.cleaned_data["fecha"]
        precio_unidad = form.cleaned_data["precio_unidad"]
        cobro_unidad = form.cleaned_data["cobro_unidad"]
        obra = Obra.objects.get(id=self.kwargs["pk"])
        trabajador = form.cleaned_data["trabajador"]

        obra.costo_total += precio_unidad * cantidad
        obra.save()

        if form.cleaned_data["tipo"] == "COSTO":
            Costo.objects.create(descripcion=descripcion, cantidad=cantidad, fecha=fecha, obra=obra, precio_unidad=precio_unidad, cobro_unidad=cobro_unidad)
        elif form.cleaned_data["tipo"] == "ACCION":
            Accion.objects.create(descripcion=descripcion, cantidad=cantidad, fecha=fecha, obra=obra, precio_unidad=precio_unidad, cobro_unidad=cobro_unidad, trabajador=trabajador)
            trabajador.acumulado += precio_unidad * cantidad
            trabajador.save()

        return super().form_valid(form)

class TrabajadorCreateView(EmpleadoRequiredMixin, CreateView):
    template_name="fachadas/crear_trabajador.html"
    form_class = TrabajadorModelForm

    def get_success_url(self):
        dict = unir_fecha(self.kwargs)
        return reverse("fachadas:detalles-obra", args=[self.kwargs["pk"], dict["año_mes"], dict["dia"]])

    def get_context_data(self, **kwargs):
        context = super(TrabajadorCreateView, self).get_context_data(**kwargs)
        dict = unir_fecha(self.kwargs)
        context.update({
            "previous":reverse("fachadas:detalles-obra", args=[self.kwargs["pk"], dict["año_mes"], dict["dia"]]) 
            })
        return context

    def form_valid(self, form):
        obra = Obra.objects.get(id=self.kwargs["pk"])
        form.instance.obra = obra
        return super().form_valid(form)

class PagoListView(EmpleadoRequiredMixin, ListView):
    template_name = 'fachadas/filtrar_pagos.html'
    queryset = Pago.objects.all()
    def get_context_data(self, **kwargs):
        context = super(PagoListView, self).get_context_data(**kwargs)
        inicio_pago = self.kwargs["inicio_pago"]
        final_pago = self.kwargs["final_pago"]
        obra = Obra.objects.get(id=self.kwargs["obra_pk"])
        pagos = Pago.objects.filter(obra=obra, 
                                    fecha__gte=inicio_pago, 
                                    fecha__lte=final_pago)
        urls = [reverse("fachadas:eliminar-pago", args=[self.kwargs["obra_pk"], inicio_pago,final_pago, i.id]) for i in pagos]
        pagos = zip(pagos, urls)
        # do something with your data
        context.update({"pagos":pagos, 
                        "obra":obra,
                        "previous":reverse("fachadas:detalles-obra", kwargs={"obra_pk": self.kwargs["obra_pk"], 
                                                                             "año_mes": date.today().strftime("%Y-%m"), 
                                                                             "dia": date.today().strftime("%d")}),
                        "inicio_pago":inicio_pago,
                        "final_pago":final_pago
                        })
        #  set your context
        return context

templates/fachadas/crear_costo.html
{% extends 'base.html' %}


{% block content %}
   <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 my-5">
         <h1>Añadir costo</h1>
         <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Guardar</button>
         </form>

      </div>
   </div>
{% endblock content %}

templates/fachadas/crear_trabajador.html
{% extends 'base.html' %}


{% block content %}
   <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 my-5">
         <h1>Añadir trabajador</h1>
         <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Guardar</button>
         </form>

      </div>
   </div>
{% endblock content %}

templates/fachadas/detalles_obra.html
{% extends 'base.html' %}

{% block content%}


   {% url 'general_usage:subir-archivo' 'obra' obra.pk as link %}
   {% include 'modals/subir_archivos.html' with link=link%}
   {% include 'modals/pagar_nomina.html' %}
   {% include 'modals/filtrar_pagos.html' %}
   {% include 'modals/crear_nota.html' with pk=obra.pk tipo='obra'%}
   <div style="text-align: center;">
      <h1>{{obra.nombre_obra}}</h1>
      <h3>Costo total de la obra:{{obra.costo_total}}</h3>
      <form action="">
         <label for="mes">Mes:</label>
         <select name="mes" id="mes" onchange="selectMonth()">
            {% for mes in meses_unicos  %}
               <option value="{{mes}}" id="{{mes}}" data-url="{% url 'fachadas:detalles-obra' obra.pk mes 32 %}">{{mes}}</option>
            {% endfor %} 
         </select>
      </form>

   </div>
   <div class="row my-1">
      <div class="col-md-6">
         <h4 class="text-center">
            Trabajadores 
            <button title="Añadir trabajador"class="btn btn-primary" onclick="location.href='{% url 'fachadas:crear-trabajador' obra.pk dict_fecha.año_mes dict_fecha.dia %}'"><i class="bi bi-person-fill-add"></i>
            </button>
            <button title="Pagar nomina" type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#modalPagarNomina">
               <i class="bi bi-currency-dollar"></i>
            </button>
            <button class="btn btn-secondary" title="Filtrar pagos" data-bs-toggle="modal" data-bs-target="#modalFiltrarPagos">
               <i class="bi bi-search"></i>
            </button>
         </h4>
         <table class="table sticky my-2" style="height: 530px;">
            <thead>
               <th>Nombre</th>
               <th>Cargo</th>
               <th>Acumulado</th>
               <th colspan="2" class="span">Ultimo Pago</th>
            </thead>
            <tbody>
               {% for trabajador, pago in trabajadores_pagos  %}
                  <tr>
                     <td class="column">{{trabajador.nombre}}</td>
                     <td class="column">{{trabajador.cargo}}</td>
                     <td class="column">{{trabajador.acumulado}}</td>
                     <td class="column">{{pago.monto}}</td>
                     <td class="column rigth">{{pago.fecha}}</td>
                  </tr>
               {% endfor %}
            </tbody>

         </table>
      </div>
      <div class="col-md-6">
         <h4 class="text-center">
            {{dict_fecha.año_mes}}-{{dict_fecha.dia}}
            <button class="btn btn-primary" title="Añadir costo" onclick="location.href='{% url 'fachadas:crear-costo' obra.pk dict_fecha.año_mes dict_fecha.dia%}'"><i class="bi bi-clipboard2-plus"></i></button>

            <button title="Añadir archivos" type="button" class="btn btn-disabled btn-secondary" data-bs-toggle="modal" data-bs-target="#modalSubirArchivos">
               <i class="bi bi-file-earmark-plus"></i>
            </button>
            <button title="Crear nota" type="button" class="btn btn-disabled btn-secondary" data-bs-toggle="modal" data-bs-target="#modalCrearNota">
               <i class="bi bi-journal-plus"></i>
            </button>
            <button title="Realizar pedido" class="btn btn-info" onclick="location.href='{% url 'general_usage:crear-pedido' 'obra' dict_fecha.fecha obra.pk %}'">
               <i class="bi bi-box-seam"></i>
            </button>

         </h4>

         <table class="table sticky my-2" style="height: 530px;" id="clientes-table">
            <thead>
               <th col-index=1>Cantidad</th>
               <th col-index=2>Descripcion</th>
               <th col-index=3>Fecha</th>
               <th col-index=4>Responsable
                  <select  class="table-filter form-select text-center" onchange="filter_rows()">
                     <option value="all">Todos</option>
                  </select>
               </th>
               <th>Precio Unidad</th>
               <th>Cobro Unidad</th>

            </thead>
            <tbody>
               {% for costo in costos %}
                  <tr>

                     <td class="column">{{costo.cantidad}}</td>
                     <td class="column">{{costo.descripcion}}</td>
                     <td class="column">{{costo.fecha}}</td>
                     <td class="column">{{costo.trabajador}}</td>
                     <td class="column">{{costo.precio_unidad}}</td>
                     <td class="column rigth">{{costo.cobro_unidad}}</td>
                  </tr>

               {% endfor %}

            </tbody>
         </table>
         <div style="text-align: center;">
            {% for dia in dias %}
               <a href="{% url 'fachadas:detalles-obra' obra.pk dict_fecha.año_mes dia %}">{{dia}}</a>
            {% endfor %}

         </div>
      </div>

   </div>
{% endblock content %}

templates/fachadas/filtrar_pagos.html
{% extends 'base.html' %}
{% block content %}
   {% include 'modals/eliminar_pago.html' %}

   <div class="text-center">
      <h2>{{obra.nombre_obra}}</h2>
      <h3>Ultimo pago: {{obra.fecha_ultimo_pago}}</h3>
      <h5>Filtros de busqueda: {{inicio_pago}}/{{final_pago}}</h5>
   </div>

   <table class="table sticky">
      <thead>
         <th>Dia del pago</th>
         <th>Periodo</th>
         <th>Trabajador</th>
         <th>Monto</th>
      </thead>
      <tbody>

         {% for pago, pago_url in pagos %}
            <tr>
               <td>
                  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalEliminarPago" title="Eliminar" onclick="setUrlModal('{{pago_url}}', 'action')"> <i class="bi bi-trash"></i></button>
                  {{pago.fecha}}</td>
               <td>{{pago.periodo_inicio|date:"Y-m-d"}}/{{pago.periodo_final|date:"Y-m-d"}}</td>
               <td>{{pago.trabajador}}</td>
               <td>{{pago.monto}}</td>
            </tr>
         {% endfor %}

      </tbody>


   </table>

{% endblock content %}

templates/fachadas/iniciar_obra.html
{% extends 'base.html' %}


{% block content %}
   <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 my-5">
 <h1>Iniciar nueva obra</h1>
      <form method="post">
         {% csrf_token %}
         {{form.as_p}}
         <button type="submit" class="btn btn-success">Guardar</button>
      </form>


      </div>
        </div>
{% endblock content %}

templates/fachadas/lista_fachadas.html
{% extends 'base.html' %}

{% block content %}
   {% include 'modals/eliminar_obra.html' %}
   <div class="row">
      <div class="col-md-12">
         <div class="table-responsive">
            <table class="table table-hover sticky table-striped align-middle" id="clientes-table">
               <thead>               
                     <th class="text-center" col-index=1>Nombre</th>
                     <th class="text-center" col-index=2>Direccion</th>
                     <th class="text-center" col-index=3>Fecha de inicio
                        <select class="table-filter form-select text-center" onchange="filter_rows()">
                           <option value="all">Todos</option>
                        </select>
                     </th>
                     <th class="text-center" col-index=4>Estado
                        <select class="table-filter form-select text-center" onchange="filter_rows()">
                           <option value="all">Todos</option>
                        </select>
                     </th>
               </thead>
               <tbody>             
                  {% for obra, obra_url in obras %}
                     <tr class="text-center">
                        <td><a href="{% url 'fachadas:detalles-obra' obra.pk año_mes dia %}">{{obra.nombre_obra}}</a> <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalEliminarObra" title="Eliminar"   onclick="setUrlModal('{{obra_url}}', 'href')"> <i class="bi bi-trash"></i></button>  </td>
                        <td>{{obra.direccion}}</td>
                        <td>{{obra.fecha_inicio}}</td>
                        <td>{{obra.estado}}</td>
                     </tr>
                  {% endfor %}
               </tbody>

            </table>
            <hr/>
            <div class="text-center">
               <a href="{% url 'fachadas:iniciar-obra' %}" class="btn btn-success align-self-lg-center" role="button">Iniciar una nueva obra</a>
            </div> 
         </div>
      </div>
   </div>
{% endblock content %}