clientes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

app_name = 'clientes'


router = DefaultRouter()
router.register(r'clientes-api', ClienteViewSet)
router.register(r'visitas', VisitaViewSet, basename='visitas')
router.register(r'llamadas', LlamadaViewSet)

crm_django/urls.py
from django.urls import include, path, re_path
from clientes.views import * 
from authentication.views import *
from clientes.urls import router as clientes_router 


urlpatterns = [
    path('', include(clientes_router.urls)),
    re_path('login-api', login),
    re_path('signup-api', signup),
]

fachadas/urls.py
from django.urls import include, path
from fachadas.views import *
app_name="fachadas"


urlpatterns = [
    path('', ObraListView.as_view(), name="lista-obra"),
    path("iniciar-obra/", ObraCreateView.as_view(), name="iniciar-obra"),
    path("<int:obra_pk>/<str:año_mes>/<str:dia>", ObraDetailView.as_view(), name="detalles-obra"),
    path("eliminar-obra/<int:pk>", ObraDeleteView.as_view(), name="eliminar-obra"),
    path("<int:pk>/<str:año_mes>/<str:dia>/añadir-costo/", CostoCreateView.as_view(), name="crear-costo"),
    path("<int:pk>/<str:año_mes>/<str:dia>/añadir-trabajador", TrabajadorCreateView.as_view(), name="crear-trabajador"),
    path("<int:pk>/<str:año_mes>/<str:dia>/pagar_nomina", pagar_nomina, name="pagar-nomina"),
    path("<int:obra_pk>/<str:inicio_pago>/<str:final_pago>/pagos/", PagoListView.as_view(), name="filtrar-pagos"),
    path("<int:obra_pk>/<str:inicio_pago>/<str:final_pago>/eliminar-pago/<int:pk>/", PagoDeleteView.as_view(), name="eliminar-pago"),
#    path("<int:obra_pk>/<str:año_mes>/<str:dia>/subir-archivo", subir_archivo, name="subir-archivo"),

    ]

inventario/urls.py
from django.urls import include, path
from inventario.views import *
app_name="inventario"

urlpatterns = [
    path('', ElementoListView.as_view(), name="lista-elementos"),
    path("crear_elemento", ElementoCreateView.as_view(), name="crear-elemento"),
    path("<int:elemento_pk>/", ElementoDetailView.as_view(), name="detalles-elemento"),
    path("eliminar/subelemento/<int:elem_pk>/<int:sub_pk>/", SubelementoDeleteView.as_view(), name="eliminar-subelemento"),
    path("editar/subelemento/<int:elem_pk>/<int:sub_pk>/", SubelementoUpdateView.as_view(), name="editar-subelemento"),
    path("eliminar/elemento/<int:elem_pk>/", ElementoDeleteView.as_view(), name="eliminar-elemento"),
    path("editar/elemento/<int:elem_pk>/", ElementoUpdateView.as_view(), name="editar-elemento")

    ]

mensajes_masivos/urls.py
from django.urls import include, path
from general_usage.views import *
from mensajes_masivos.views import MensajeCreateView, MensajeListView
app_name="mensajes_masivos"

urlpatterns = [
        path("programar-mensaje", MensajeCreateView.as_view(), name="programar-mensaje"),
        path("lista-mensajes/", MensajeListView.as_view(), name="lista-mensajes")

        ]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>DJCRM</title>
      <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"> -->           

      <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
      <link rel="stylesheet" href="{% static 'css/timeline.css' %}">
      <link rel="stylesheet" href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.css' %}">
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">
      <link rel="stylesheet" href="{% static 'node_modules/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
      <style>
select { width: 5.5em }
      </style>
   </head>
   <body>
      {% include "navbar.html" %}
      <div class="container-fluid " style="padding: 30px;">      
         {% block content %}


         {% endblock content %}
      </div>
      {% include "scripts.html" %}
   </body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}

   <div class="d-flex flex-column justify-content-center align-align-items-center col-4 mx-auto" style="" >
   {% load static %}
      <img src=" {% static 'img/logo-doctor-clean.png' %}" alt="">
      <form action="" method="post">
         {% csrf_token %}
         {{form.as_p}}
        <div class="mx-auto col-2"> <button type="submit" class="btn btn-success">Iniciar Sesion</button></div>
      </form>


   </div>



  {% endblock content %}

templates/navbar.html
{% load static %}
{% url 'landing-page' as landing_url %}
{% url 'clientes:lista-cliente' as lista_url %}
{% url 'fachadas:lista-obra' as fachadas_url %}
{% url 'inventario:lista-elementos' as inventario_url %}
{% url 'mensajes_masivos:lista-mensajes' as mensajes_url%}
{% url 'mensajes_masivos:lista-mensajes' as mensajes_url%}
{% url 'empleados:lista-empleados' as empleados_url%}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" data-bs-theme="dark">
   <div class="container-fluid">
      {% comment "show the back button only no necessary pages." %}{% endcomment %}
      {% if request.path != landing_url and request.path != lista_url and request.path != fachadas_url and request.path != inventario_url and request.path != mensajes_url and request.path != empleados_url %}
      <button onclick="location.href='{{previous}}'" class="btn btn-secondary" title="Volver a la pagina previa"><i class="bi bi-arrow-left-square"></i></button>
      {% endif %}

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">

         <div class="navbar-nav">
            <img src="{% static 'img/logo-doctor-clean.png' %}" class="logo">
            {% if request.user.is_authenticated%}
            {% if request.user.clientes %}
            <a class="nav-link " href="{% url 'clientes:lista-cliente' %}">Clientes</a>  
            {% endif %}
            {% if request.user.fachadas%}
            <a class="nav-link " href="{% url 'fachadas:lista-obra' %}">Fachadas</a> 
            {% endif %}
            {% endif %}
            {% if request.user.inventario %}
            <a class="nav-link " href="{% url 'inventario:lista-elementos' %}">Inventario</a> 
            {% endif %}

            {% if request.user.is_organisor %}
            <a class="nav-link" href="{% url 'empleados:lista-empleados' %}">Empleados</a>
            {% endif %}

            {% if request.user.mensajes %}
            <a href="{{mensajes_url}}" class="nav-link">Mensajes Masivos</a>

            {% endif %}
         </div>
         <div class="navbar-nav ms-auto">
            {% if request.user.is_authenticated %}
            <span class="navbar-text">Perfil: {{request.user.username}}</span> 
            <a class ="mx-3  nav-link" href="{% url 'logout' %}">Cerrar sesion</a>
            {% comment "Navbar button for searching clientes in DB" %}{% endcomment %}
               {% if request.path == lista_url %}
               <form class="d-flex" role="search" method="post" action="{{lista_url}}">
                  {% csrf_token %}
                  <input class="form-control me-2"type="search" aria-label="Search" name="searched">
                  <select name="filtro" class="form-select">
                     <option value="nombre">Nombre</option>
                     <option value="nit">NIT</option>
                     <option value="administrador">Administrador</option>
                  </select>
               {% elif request.path == inventario_url%}
               <form class="d-flex" role="search" method="post" action="{{inventario_url}}">
                  {% csrf_token %}
                  <input class="form-control me-2"type="search" aria-label="Search" name="searched">
                  <select name="filtro" class="form-select">
                     <option value="descripcion">Descripcion</option>
                     <option value="codigo">Codigo</option>
                  </select>
               {% elif request.path == empleado_detalles%}
               <form class="d-flex" role="search" method="post" action="{{empleado_detalles}}">
                  {% csrf_token %}
                  <input class="form-control me-2"type="search" aria-label="Search" name="searched">
                  <select name="filtro" class="form-select">
                     <option value="cliente">Cliente</option>
                  </select>
               {% endif %}
               <button class="btn btn-outline-secondary" type="submit">Buscar</button>
            </form>
            {% else %}
               <a class="nav-link" href="{% url 'signup' %}">Registrarse</a>
            {% endif %}

         </div>
      </div>
   </div>
</nav>

templates/scripts.html
{% load static %}

<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>
<!--Obligatorio que la libreria datepicker este en el footer justo despues de los js de bootstrap para no causar conflicto-->
<script src="{% static 'node_modules/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'node_modules/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}"></script>

<script src="{% static 'js/filter.js' %}">
   getUniqueValuesFromColumn()
</script>

<script src="{% static 'js/datepicker.js' %}">
</script>

<script src="{% static 'js/form.js' %}">
   start_form()
</script>

<script src="{% static 'js/load_data.js' %}">

</script>


<script src="{% static 'js/functions.js' %}"></script>
<script data-visitas="{{visitas_vigentes}}" data-nombre="{{cliente.nombre_orgnanizacion}}">
   getUniqueValuesFromColumn()
   datepicker()
 
</script>

templates/search_clientes.html
{% extends 'clientes/lista_clientes.html' %}

{% block titulo %}
   <h1 class="text-center">Resultados de la busqueda</h1>
{% endblock titulo %}

templates/sidebar.html
<div class="container-fluid">
   <div class="row flex-nowrap">
      <div class="col-auto px-0">
         <div id="sidebar" class="collapse collapse-horizontal show border-end">
            <div id="sidebar-nav" class="list-group border-0 rounded-0 text-sm-start min-vh-100">
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-bootstrap"></i> <span>Item</span> </a>
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-film"></i> <span>Item</span></a>
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-heart"></i> <span>Item</span></a>
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-bricks"></i> <span>Item</span></a>
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-clock"></i> <span>Item</span></a>
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-archive"></i> <span>Item</span></a>
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-gear"></i> <span>Item</span></a>
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-calendar"></i> <span>Item</span></a>
               <a href="#" class="list-group-item border-end-0 d-inline-block text-truncate" data-bs-parent="#sidebar"><i class="bi bi-envelope"></i> <span>Item</span></a>
            </div>
         </div>
      </div>
   </div>
</div>