clientes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

app_name = 'clientes'


router = DefaultRouter()
router.register(r'clientes-api', ClienteViewSet)
router.register(r'visitas', VisitaViewSet, basename='visitas')
router.register(r'llamadas', LlamadaViewSet)

crm_django/urls.py
from django.urls import include, path, re_path
from clientes.views import * 
from authentication.views import *
from clientes.urls import router as clientes_router 


urlpatterns = [
    path('', include(clientes_router.urls)),
    re_path('login-api', login),
    re_path('signup-api', signup),
]

general_usage/urls.py
from django.urls import include, path
from general_usage.views import *
app_name="general_usage"


urlpatterns=[
        path("crear_nota/<str:tipo>/<int:pk>/", NotaCreateView.as_view(), name="crear-nota"),
        path("subir_archivo/<str:tipo>/<int:pk>/", ArchivoCreateView.as_view(), name="subir-archivo"),
        path("crear-pedido/<str:tipo>/<str:fecha>/<int:pk>/", PedidoFormsetView.as_view(), name="crear-pedido"),
        path('ajax/cargar_subelementos', cargar_subelementos, name='ajax_cargar_subelementos'), # AJAX
        path("detalles_pedido/<int:pedido_pk>/", PedidoDetailView.as_view(), name="detalles-pedido"),
        path("lista-objetos/<str:tipo>/<str:fecha>/<int:pk>/", ObjetoListView.as_view(), name="lista-objetos"),
        ]

inventario/urls.py
from django.urls import include, path
from inventario.views import *
app_name="inventario"

urlpatterns = [
    path('', ElementoListView.as_view(), name="lista-elementos"),
    path("crear_elemento", ElementoCreateView.as_view(), name="crear-elemento"),
    path("<int:elemento_pk>/", ElementoDetailView.as_view(), name="detalles-elemento"),
    path("eliminar/subelemento/<int:elem_pk>/<int:sub_pk>/", SubelementoDeleteView.as_view(), name="eliminar-subelemento"),
    path("editar/subelemento/<int:elem_pk>/<int:sub_pk>/", SubelementoUpdateView.as_view(), name="editar-subelemento"),
    path("eliminar/elemento/<int:elem_pk>/", ElementoDeleteView.as_view(), name="eliminar-elemento"),
    path("editar/elemento/<int:elem_pk>/", ElementoUpdateView.as_view(), name="editar-elemento")

    ]

inventario/models.py
from datetime import date
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

# Create your models here.

class Elemento(models.Model):
    CHOCIES_CATEGORIA = (("HERRAMIENTA", "Herramienta"), ("INSUMO", "Insumo"))
    codigo_general = models.IntegerField(unique=True)
    descripcion = models.CharField(max_length=30)
    categoria = models.CharField(choices=CHOCIES_CATEGORIA, max_length=30)
    fecha = models.DateField(default=date.today())
    
    def __str__(self):
        return f"{self.codigo_general}-{self.descripcion}"
class Subelemento(models.Model):
    cantidad = models.IntegerField(default=1)
    codigo_unico = models.IntegerField()
    marca = models.CharField(max_length=30)
    elemento = models.ForeignKey("inventario.Elemento", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.codigo_unico} - {self.marca}"

inventario/forms.py
from django import forms
from django.forms import widgets
from .models import *

dict_widget = {"class":"form-control"}

class ElementoModelForm(forms.ModelForm):
    class Meta:
        model = Elemento
        fields = ("codigo_general",
                  "descripcion",
                  "categoria"
                )
        widgets = {"codigo_general": forms.NumberInput(attrs={"class": "form-control"}),
                   "descripcion": forms.TextInput(attrs={"class": "form-control"}),
                   "categoria": forms.Select(attrs={"class": "form-control"}),
                   }

class SubelementoModelForm(forms.ModelForm):
    class Meta:
        model = Subelemento
        fields = ("codigo_unico",
                  "marca",
                  "cantidad")
        widgets = {"codigo_unico": forms.NumberInput(attrs=dict_widget),
                   "marca": forms.TextInput(attrs=dict_widget),
                   "cantidad": forms.NumberInput(attrs=dict_widget)}

inventario/views.py
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, FormView, ListView, UpdateView
from general_usage.models import Grupo_Pedido

from inventario.models import *
from inventario.forms import *

class ElementoListView(ListView):
    template_name="inventario/lista_elementos.html"
    queryset = Elemento.objects.all().order_by("-codigo_general")
    object_list = Elemento.objects.all() 
    context_object_name = "elementos"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pedidos = Grupo_Pedido.objects.filter(estado="EN PROCESO")
        context.update({"pedidos":pedidos})
        return context

    def post(self, request, **kwargs):
        searched = request.POST["searched"]
        filtro = request.POST["filtro"]
        elementos = []
        if filtro == "descripcion":
            elementos = Elemento.objects.filter(descripcion__icontains=searched)
        elif filtro == "codigo":
            elementos = Elemento.objects.filter(codigo_general__icontains=searched)
        context = {"elementos":elementos}
        return super(ElementoListView, self,).render_to_response(context)
    
class ElementoDetailView(FormView):
    template_name="inventario/detalles_elemento.html"
    form_class = SubelementoModelForm

    def get_success_url(self):
        return reverse("inventario:detalles-elemento", args=[self.kwargs["elemento_pk"]])

    def get_context_data(self, **kwargs):
        context = super(ElementoDetailView, self).get_context_data(**kwargs)
        elemento = Elemento.objects.get(id=self.kwargs["elemento_pk"])
        subelementos = Subelemento.objects.filter(elemento=elemento)
        urls = [reverse("inventario:eliminar-subelemento", args=[self.kwargs["elemento_pk"], i.id]) for i in subelementos]
        subelementos = zip(subelementos, urls)
        context.update({
            "elemento":elemento,
            "subelementos": subelementos,
            "previous": reverse("inventario:lista-elementos")
            })
        return context

    def form_valid(self, form):
        elemento = Elemento.objects.get(id=self.kwargs["elemento_pk"])
        form.instance.elemento =elemento
        form.save()
        return super().form_valid(form)


class ElementoCreateView(CreateView):
    template_name = "inventario/crear_elemento.html"
    model = Elemento
    form_class = ElementoModelForm

    def get_success_url(self):
        return reverse("inventario:lista-elementos")

    def get_context_data(self, **kwargs):
        context = super(ElementoCreateView, self).get_context_data(**kwargs)
        context.update(
                {"previous":reverse("inventario:lista-elementos")})
        return context

class ElementoUpdateView(UpdateView):
    template_name="inventario/editar_elemento.html"
    model = Elemento
    form_class = ElementoModelForm
    pk_url_kwarg = "elem_pk"

    def get_success_url(self):
        return reverse("inventario:detalles-elemento", args=[self.kwargs["elem_pk"]])
    def get_context_data(self, **kwargs):
        context = super(ElementoUpdateView, self).get_context_data(**kwargs)
        context.update({
            "previous": reverse("inventario:detalles-elemento", args=[self.kwargs["elem_pk"]])    
            })
        return context

class ElementoDeleteView(DeleteView):
    model = Elemento
    http_method_names = ['delete']
    pk_url_kwarg = "elem_pk"

    def dispatch(self, request, *args, **kwargs):
        handler = getattr(self, 'delete')
        return handler(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('inventario:lista-elementos')

class SubelementoUpdateView(UpdateView):
    template_name = "inventario/editar_subelemento.html"
    model = Subelemento
    form_class = SubelementoModelForm
    pk_url_kwarg = "sub_pk"

    def get_success_url(self):
        return reverse("inventario:detalles-elemento", args=[self.kwargs["elem_pk"]])
    def get_context_data(self, **kwargs):
        context = super(SubelementoUpdateView, self).get_context_data(**kwargs)
        context.update({
            "previous": reverse("inventario:detalles-elemento", args=[self.kwargs["elem_pk"]])    
            })
        return context

class SubelementoDeleteView(DeleteView):
    model = Subelemento
    http_method_names = ['delete']
    pk_url_kwarg = "sub_pk"

    def dispatch(self, request, *args, **kwargs):
        handler = getattr(self, 'delete')
        return handler(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('inventario:detalles-elemento', args=[self.kwargs["elem_pk"]])

templates/inventario/crear_elemento.html
{% extends 'base.html' %}
{% block content %}
   <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 my-5">
         <h1>Registrar elemento</h1>
         <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Guardar</button>
         </form>

      </div>
   </div>


{% endblock content %}

templates/inventario/detalles_elemento.html
{% extends 'base.html' %}

{% block content %}
   {% url 'inventario:eliminar-elemento' elemento.pk as eliminar_url %}
   {% include 'modals/eliminar_subelemento.html' %}
   {% include 'modals/eliminar_cliente.html' with link=eliminar_url object="Elemento"%}

   <div class="row">
      <div class="col-4">
         <div class="text-center">
            <h3>{{elemento.descripcion}}</h3>
            <h5>{{elemento.categoria}}</h5>
            <h5>Codigo: {{elemento.codigo_general}}</h5>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalEliminar" title="Eliminar">
               <i class="bi bi-trash"></i>
            </button>
            <a href="{% url 'inventario:editar-elemento' elemento.pk %}" class="btn btn-warning">
               <i class="bi bi-clipboard-plus"></i>
            </a>
         </div>
         <div class="row">
            <div class="col-md-1"></div>
            <form method="post" class="my-5 col-md-10">
               <h4 class="text-center">Registro de subelemento</h4>
               {% csrf_token %}
               {{form.as_p}}
               <div style="text-align: center;">
                  <button type="submit" class="btn btn-success">Registrar</button>
               </div>
            </form> 
         </div>
      </div>
      <div class="col-8">
         <table class="table sticky">
            <thead>
               <th>Codigo unico</th>
               <th>Cantidad</th>
               <th>Marca</th>
               <th>Acciones</th>
            </thead>
            <tbody>
               {% for subelemento, subelemento_url in subelementos %}
                  <tr>
                     <td>{{subelemento.codigo_unico}}</td>
                     <td>{{subelemento.cantidad}}</td>
                     <td>{{subelemento.marca}}</td>
                     <td> 
                        <button class="btn btn-danger" title="Eliminar" data-bs-toggle="modal" data-bs-target="#modalEliminarSubelemento" onclick="setUrlModal('{{subelemento_url}}', 'url-eliminar-subelemento')">
                           <i class="bi bi-trash"></i>
                        </button>
                        <button class="btn btn-primary" title="Editar" onclick="location.href='{% url 'inventario:editar-subelemento' elemento.pk subelemento.pk %}'">
                           <i class="bi bi-clipboard-plus"></i>
                        </button>
                     </td>
                  </tr>
               {% endfor %}
            </tbody>
         </table>
      </div>
   </div>

{% endblock content %}

templates/inventario/editar_elemento.html
{% extends 'base.html' %}

{% block content %}
   <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 my-5">
         <h1>Editar datos del elemento: {{elemento}}</h1>

         <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div style="text-align: center;">
               <button type="submit" class="btn btn-success">Guardar</button>
            </div>
         </form>

      </div>
   </div>

{% endblock content %}

templates/inventario/editar_subelemento.html
{% extends 'base.html' %}

{% block content %}
   <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 my-5">
         <h1>Editar datos del subelemento: {{subelemento}}</h1>

         <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div style="text-align: center;">
               <button type="submit" class="btn btn-success">Guardar</button>
            </div>
         </form>

      </div>
   </div>

{% endblock content %}

templates/inventario/lista_elementos.html
{% extends 'base.html' %}
{% block content %}

   <div class="row">
      <div class="col-md-8">
         <table class="table sticky" id="clientes-table">
            <h1 class="text-center">Elementos</h1>
            <thead>
               <th col-index=1>Codigo general</th>
               <th col-index=2>Descripcion</th>
               <th col-index=3>Categoria
                  <select class="table-filter form-select text-center" onchange="filter_rows()">
                     <option value="all">Todos</option>
                  </select>

               </th>
               <th>Fecha de registro</th>
            </thead>

            <tbody>
               {% for elemento in elementos  %}
                  <tr>
                     <td><a href="{% url 'inventario:detalles-elemento' elemento.pk %}">
                           {{elemento.codigo_general}}
                        </a></td>
                        <td>{{elemento.descripcion}}</td> 
                        <td>{{elemento.categoria}}</td>
                        <td>{{elemento.fecha}}</td>
                  </tr>
               {% endfor %}
            </tbody>

         </table>
         <hr>
         <div class="text-center">
            <a class="btn btn-success" href="{% url 'inventario:crear-elemento' %}">Registrar elemento</a> 
         </div>


      </div>
      <div class="col-md-4 text-center">
         <h1>Pedidos pendientes</h1>
         {% for pedido in pedidos  %}
            <div class="conatiner-pedido">
               <h3>
                  <a href="{% url 'general_usage:detalles-pedido' pedido.pk %}">
                 <i class="bi bi-box-seam"></i>

                  </a>
                 {{pedido.fecha | date:"d/m/Y-G:i"}}
               </h3> 
            </div>
         {% endfor %}
      </div>
   </div>


{% endblock content %}