clientes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

app_name = 'clientes'


router = DefaultRouter()
router.register(r'clientes-api', ClienteViewSet)
router.register(r'visitas', VisitaViewSet, basename='visitas')
router.register(r'llamadas', LlamadaViewSet)

crm_django/urls.py
from django.urls import include, path, re_path
from clientes.views import * 
from authentication.views import *
from clientes.urls import router as clientes_router 


urlpatterns = [
    path('', include(clientes_router.urls)),
    re_path('login-api', login),
    re_path('signup-api', signup),
]

general_usage/urls.py
from django.urls import include, path
from general_usage.views import *
app_name="general_usage"


urlpatterns=[
        path("crear_nota/<str:tipo>/<int:pk>/", NotaCreateView.as_view(), name="crear-nota"),
        path("subir_archivo/<str:tipo>/<int:pk>/", ArchivoCreateView.as_view(), name="subir-archivo"),
        path("crear-pedido/<str:tipo>/<str:fecha>/<int:pk>/", PedidoFormsetView.as_view(), name="crear-pedido"),
        path('ajax/cargar_subelementos', cargar_subelementos, name='ajax_cargar_subelementos'), # AJAX
        path("detalles_pedido/<int:pedido_pk>/", PedidoDetailView.as_view(), name="detalles-pedido"),
        path("lista-objetos/<str:tipo>/<str:fecha>/<int:pk>/", ObjetoListView.as_view(), name="lista-objetos"),
        ]

clientes/models.py
from datetime import datetime
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.contrib.auth.models import AbstractUser

# Create your models here.

#User class for all of our users. The "type" of user, 
#is stablished by a forgein key from an instance of the diferent kind of users
#to this class
class User(AbstractUser):
    is_organisor = models.BooleanField(default=False)
    clientes = models.BooleanField(default=False)
    inventario = models.BooleanField(default=False)
    fachadas = models.BooleanField(default=False)
    mensajes = models.BooleanField(default=False)
    email = models.EmailField(null=False)

class Cliente(models.Model):

    CHOICES_ESTADO = (("INACTIVO", "Inactivo"), ("POTENCIAL", "Potencial"))
    CHOICES_SERVICIO = (("VENCIDO", "Vencido"), ("GARANTIA", "Garantia"), ("EN TERMINOS", "En terminos"))
    nombre_orgnanizacion = models.CharField(max_length=150)
    direccion = models.CharField(max_length=255)
    apartamentos = models.CharField(max_length=50)
    nit = models.CharField(max_length=15)
    correo = models.EmailField(null=True)
    frecuencia_meses = models.IntegerField(default=1)
    empleado = models.ForeignKey("Empleado", on_delete=models.SET_NULL, null=True)
    fecha_vencimiento = models.DateField(null=True, default=None)
    administrador = models.CharField(max_length=150)
    supervisor = models.CharField(max_length=50)
    telefono_supervisor = models.CharField(max_length=30)
    correo_supervisor = models.EmailField()
    telefono = models.CharField(max_length=30)
    estado = models.CharField(max_length=20, choices = CHOICES_ESTADO)
    rechazos = models.IntegerField(default=0, null=False)
    estado_servicio = models.CharField(max_length=15, choices=CHOICES_SERVICIO)
    def __str__(self):
        return f"{self.nombre_orgnanizacion}"
  
class Empleado(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

#class Visita(models.Model):
#    CHOICES_ESTADO = (("FINALIZADA", "Finalizada"), ("EN PROCESO", "En proceso"))
#
#    fecha = models.DateField()
#    observaciones = models.TextField()
#    cliente = models.ForeignKey("clientes.Cliente", on_delete=models.CASCADE)
#    estado = models.CharField(max_length=15, choices=CHOICES_ESTADO)
#    def __str__(self):
#        return f"{self.fecha}"

#class Llamada(models.Model):
#
#    CHOICES_ESTADO = (("REALIZADA", "Realizada"), ("PENDIENTE", "Pendiente"))
#    fecha = models.DateField()
#    cliente = models.ForeignKey("clientes.Cliente", on_delete=models.CASCADE)
#    observaciones = models.TextField()
#    estado = models.CharField(max_length=15, choices=CHOICES_ESTADO, default="PENDIENTE")

class Interaccion(models.Model):
    CHOICES_ESTADO = (("FINALIZADA", "Finalizada"), ("EN PROCESO", "En proceso"), ("PENDIENTE", "Pendiente"))
    fecha = models.DateField()
    fecha_creacion = models.DateField(auto_now_add=True)
    observaciones = models.CharField(max_length=255)
    cliente = models.ForeignKey("clientes.Cliente", on_delete=models.CASCADE)
    estado = models.CharField(max_length=20, choices=CHOICES_ESTADO, default="EN PROCESO")
    empleado = models.ForeignKey("clientes.Empleado", on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return f"{self.fecha}"

class Visita(Interaccion):
    pass
class Llamada(Interaccion):
    def __init__(self, *args, **kwargs):
        super(Llamada, self).__init__(*args, **kwargs)
        if self.estado=="EN PROCESO":
            self.estado = "PENDIENTE"

#signal to execute when an user is created
def post_user_created_signal(sender, instance, created, **kwargs):
    if created and not instance.is_organisor:
      Empleado.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

clientes/views.py
from datetime import date, timedelta
from shutil import rmtree
from dateutil import relativedelta as rd

from django.contrib.auth.views import LoginView, reverse_lazy
#from django.http import HttpResponseForbidden, request
from django.shortcuts import HttpResponse, redirect, render


from django.urls import reverse
from django.views.generic import CreateView, DeleteView, DetailView, FormView, ListView, UpdateView
from clientes.functions import *
from clientes.mixins import EmpleadoRequiredMixin
from functions import *

#from clientes.forms import ClienteForm
from .models import Cliente, Empleado, Llamada
from .models import Visita
from .forms import * 

import os
import json

CARPETA_FUMIGACION = "/mnt/INFO_VARIA/CLIENTES"

class SingupView(CreateView):
    template_name="registration/register.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("landing-page")
#    def form_valid(self,form):
#        if form.instance.clientes or form.instance.inventario or form.instance.fachadas:
#            form.instance.is_organisor = False
#        form.save()
#        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"previous":self.get_success_url()})
        return context

class LandingPageView(LoginView):
    form_class = LoginForm  
    template_name = "landing.html"

    def get(self, request, *args, **kwargs):
        #Redirect user to the clients app if it's authenticated.
        if request.user.is_authenticated:
            if request.user.is_organisor:
              return redirect("empleados:lista-empleados" )
            elif request.user.clientes:
                return redirect("clientes:lista-cliente")
            elif request.user.fachadas:
                return redirect("fachadas:lista-obra")
            elif request.user.mensajes:
                return redirect("mensajes_masivos:lista-mensajes")
        return super(LandingPageView, self).get(request, *args, **kwargs)

class ClienteListView( EmpleadoRequiredMixin ,ListView):
    template_name = "clientes/lista_clientes.html"
    context_object_name = "clientes"
    queryset = Cliente.objects.all()   
    object_list = Cliente.objects.all()

    def post(self, request, **kwargs):
        searched = request.POST["searched"]
        filtro = request.POST["filtro"]
        clientes = []
        if filtro == "nombre":
            clientes = self.object_list.filter(nombre_orgnanizacion__icontains=searched)
        elif filtro == "nit":
            clientes = self.object_list.filter(nit__icontains=searched)
        elif filtro == "administrador":
            clientes = self.object_list.filter(administrador__icontains=searched)
        context = {"clientes":clientes}
        return super(ClienteListView, self,).render_to_response(context)


#This view provides details of the client model, as well as 
#allows the user to create new visits. For this, a creatview class
#is used, and the context is updated with the necessary data for the forms
#and the details of data to work.
class ClienteDetailView(EmpleadoRequiredMixin, FormView):
    template_name = "clientes/detalles_clientes.html"
    form_class= InteraccionForm
   
    def get_success_url(self):
        #Args receives a list with arguments
        return reverse("clientes:detalles-cliente", args=[self.kwargs['pk']])

    def get_context_data(self, **kwargs):
        context = super(ClienteDetailView, self).get_context_data(**kwargs)
        visitas_cliente = Visita.objects.filter(cliente_id=self.kwargs["pk"]).order_by("-fecha")
        llamadas = Llamada.objects.filter(cliente_id=self.kwargs["pk"]).order_by("-fecha")
        interacciones_cliente= sorted(list(visitas_cliente) + list(llamadas), key=lambda x: x.fecha, reverse=True)
        tipos = [definir_tipos(i) for i in interacciones_cliente]
        visibilidades = ["disabled" if i.fecha > date.today() else "" for i in interacciones_cliente]
        interacciones_cliente = zip(interacciones_cliente, tipos, visibilidades)
        
        visitas_vigentes = Visita.objects.filter(fecha__gte = datetime.today()).values("fecha", "cliente__nombre_orgnanizacion")
#        fechas_usadas = [i.fecha.strftime("%Y-%m-%d") for i in visitas_vigentes]
        for i in visitas_vigentes:
            i["fecha"] = i["fecha"].strftime("%Y-%m-%d")

        #Update the context with our necessary queries
        context.update({
            "visitas_cliente": visitas_cliente,
            "llamadas": llamadas,
            "interacciones_cliente": interacciones_cliente,
            "cliente":Cliente.objects.get(id=self.kwargs["pk"]),
            "previous":reverse("clientes:lista-cliente"), #Link to back button on navbar
            #"fechas_usadas":fechas_usadas,
            "visitas_vigentes":json.dumps(list(visitas_vigentes))
            }) 
        return context

    def get_form_kwargs(self):
        #pass kwarg with last visit
        kwargs = super().get_form_kwargs()
        kwargs["ultima_visita"] = Visita.objects.filter(cliente_id=self.kwargs["pk"]).order_by("-fecha").first()
        return kwargs

    #Manually setting values for the form
    def form_valid(self, form):
        cliente = Cliente.objects.get(id=self.kwargs["pk"])
        visitas = Visita.objects.filter(cliente_id=self.kwargs["pk"]).order_by("-fecha")
        fecha = form.cleaned_data["fecha"]
        observaciones = form.cleaned_data["observaciones"]
        empleado = Empleado.objects.get(user=self.request.user)
    #our form is a generic one which can be used for creating multiple subclasses of the interaction parent class
        if form.cleaned_data["tipo"] == "VISITA":
            carpeta = fecha.strftime('%Y-%m-%d')
            Visita.objects.create(fecha=fecha, observaciones=observaciones, cliente=cliente, empleado=empleado)
            if visitas.count() == 0:
                cliente.estado = "ACTIVO"
            cliente.rechazos = 0
            
            ruta = os.path.join(CARPETA_FUMIGACION, cliente.nombre_orgnanizacion, carpeta)
            create_folder(ruta)
            if cliente.estado == "INACTIVO":
                cliente.estado = "ACTIVO"
            cliente.save()

        elif form.cleaned_data["tipo"] == "LLAMADA":
            Llamada.objects.create(fecha=fecha, observaciones=observaciones, cliente=cliente, empleado=empleado)
   

        return super().form_valid(form)

class ClienteDetail2View(EmpleadoRequiredMixin, DetailView):
    template_name="clientes/detalles_cliente2.html"
    model=Cliente
    context_object_name="cliente"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "previous": reverse("clientes:detalles-cliente", args=[self.kwargs["pk"]])
            })
        return context

class ClienteCreateView(EmpleadoRequiredMixin, CreateView):
    template_name = "clientes/crear_cliente.html"
    form_class=ClienteModelForm

    def get_success_url(self):
        return reverse("clientes:lista-cliente")
    
    def get_form_kwargs(self):
        #pass user instance as an argument for the form
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(ClienteCreateView, self).get_context_data(**kwargs)
        context.update({
            "previous":reverse("clientes:lista-cliente")
            })
        return context

    def form_valid(self, form):
        #Allow organisor users to assing clients to agents.
        if self.request.user.is_organisor:
            empleado_username = form.cleaned_data["empleado_field"]
            form.instance.empleado = Empleado.objects.get(user__username = empleado_username)
        else:
            form.instance.empleado = Empleado.objects.get(user = self.request.user)
        ruta = os.path.join(CARPETA_FUMIGACION, form.instance.nombre_orgnanizacion)
        create_folder(ruta)
        
    
        return super(ClienteCreateView, self).form_valid(form)

class ClienteUpdateView(EmpleadoRequiredMixin, UpdateView):
    template_name = "clientes/actualizar_cliente.html"
    queryset = Cliente.objects.all()
    form_class = ClienteModelFormUpdate

    def get_success_url(self):
        #The details-client function receives 2 arguments: request and the pk.
        return reverse("clientes:detalles-cliente", args=[self.kwargs['pk']])

    def get_form_kwargs(self):
        #ppas user instance as a kwarg, for form edition.
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(ClienteUpdateView, self).get_context_data(**kwargs)
        #Update the context with our necessary queries
        context.update({
            "previous":reverse("clientes:detalles-cliente", args=[self.kwargs["pk"]]) #Link to back button on navbar
            })
        return context


    def form_valid(self, form):
        #TODO send email
        if self.request.user.is_organisor:
            empleado_username = form.cleaned_data["empleado_field"]
            form.instance.empleado = Empleado.objects.get(user__username = empleado_username)
        src = os.path.join(CARPETA_FUMIGACION, self.get_object().nombre_orgnanizacion)
        dst = os.path.join(CARPETA_FUMIGACION, form.instance.nombre_orgnanizacion)
        try:
            os.rename(src, dst)
        except:
            pass
        return super(ClienteUpdateView, self).form_valid(form) 


class ClienteDeleteView(EmpleadoRequiredMixin, DeleteView):

    model = Cliente
    http_method_names = ['delete']

    def dispatch(self, request, *args, **kwargs):
        instance = Cliente.objects.get(id=self.kwargs["pk"])
        carpeta = os.path.join(CARPETA_FUMIGACION, instance.nombre_orgnanizacion)
        try:
            rmtree(carpeta)

templates/clientes/actualizar_cliente.html
{% extends 'base.html' %}

{% block content %}
   <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 my-5">
         <h1>Editar datos del cliente: {{cliente}}</h1>

         <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <div style="text-align: center;">
               <button type="submit" class="btn btn-success">Guardar</button>
            </div>
         </form>

      </div>
   </div>

{% endblock content %}

templates/clientes/crear_cliente.html
{% extends 'base.html' %}


{% block content %}
   <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4 my-5">
         <h1>Registrar nuevo cliente</h1>
         <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-success">Guardar</button>
         </form>

      </div>
   </div>
{% endblock content %}

templates/clientes/detalles_cliente2.html
{% extends 'base.html' %}
{% block content %}

   <div class="text-center">
      <h1>{{cliente.nombre_orgnanizacion}}</h1>
      <hr>
      <h3>Direccion: {{cliente.direccion}}</h3>
      <h3>Apartamentos: {{cliente}}</h3>
      <h3>Nit: {{cliente.nit}}</h3>
      <h3>Frecuencia (meses): {{cliente.frecuencia_meses}}</h3>

      <h3>Administrador: {{cliente.administrador}}</h3>
      <h3>Telefono Administrador: {{cliente.telefono}}</h3>
      <h3>Correo Administrador: {{cliente.correo}}</h3>

      <h3>Supervisor: {{cliente.supervisor}}</h3>
      <h3>Telefono supervisor: {{cliente.telefono_supervisor}}</h3>
      <h3>Correo supervisor: {{cliente.correo_supervisor}}</h3>
      <h3>Estado: {{cliente.estado}}</h3>
   </div>

{% endblock content %}

templates/clientes/detalles_clientes.html
{% extends 'base.html' %}
{% block content %}
   {% include 'modals/subir_archivos.html'%}
   {% include 'modals/crear_nota.html' %}
   {% include 'modals/reprogramar_visita.html' %}
   {% include 'modals/finalizar_visita.html' %}
   <div class="row">
      <div class="col-md-3 info-parent"> 
         <div class="row text-center info-cliente" >
            <h1>
               <a href="{% url 'clientes:detalles-cliente2' cliente.pk %}">
                  {{cliente}}
               </a>
            </h1>
            <h3>{{cliente.direccion}}</h3>
            <h5>Estado del cliente: {{cliente.estado}}</h5>

            {% if cliente.estado == "ACTIVO" %}      
               {% with visitas_cliente|first as visita %}
                  <h5>Estado de la ultima visita: {{visita.estado}}</h5>
               {% endwith %}
            {% endif %}
            {% if cliente.fecha_vencimiento != None %}
               <h5>Vencimiento: {{cliente.fecha_vencimiento}}</h5>
            {% endif %}
            <div class="text-center">

               <a href="{% url 'clientes:actualizar-cliente' cliente.pk%}" class="btn btn-warning" title="Editar">
                  <i class="bi bi-clipboard2-plus"></i>
               </a>                                                
               {% url 'clientes:eliminar-cliente' cliente.pk as eliminar_url%} 
               {% include "modals/eliminar_cliente.html" with link=eliminar_url object="cliente" %}
               <!-- Button trigger modal -->
               <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalEliminar" title="Eliminar">
                  <i class="bi bi-trash"></i>
               </button>
            </div>
         </div>

         <div class="row my-3">
            <h2 class="text-center">Programar visita/llamada</h2>
            <div class="text-center">
               {% with llamadas|first as llamada  %}
                  {% if llamadas.count != 0 and llamada.estado != "FINALIZADA"%}
                     Cantidad de rechazos por parte del cliente: {{cliente.rechazos}} 

                  {% endif %}
               {% endwith %}

            </div>

            <form method="post">
               {% csrf_token %}
               {{form.as_p}}
               <div id="fecha_repetida_form" class="text-center"></div>
               <div class="text-center">
                  <button type="submit" class="btn btn-success"> Guardar</button>
               </div>

            </form>
         </div>

      </div>
      <div class="col-md-9">
         <div class="row">
            {% if interacciones_cliente.count != 0 %}

               <table class="table table-hover sticky" id="clientes-table">
                  <h2 class="text-center">Interacciones</h2>
                  <thead>
                     <tr >
                        <th col-index=1>Fecha</th>
                        <th col-index=2>Observaciones</th>
                        <th col-index=3>Tipo
                           <select  class="table-filter form-select text-center"   onchange="filter_rows()">
                              <option value="all">Todos</option>
                           </select>
                        </th>
                        <th>Acciones</th>
                     </tr>
                  </thead>

                  <tbody>                     
                     {% for interaccion, tipo, visibilidad1 in interacciones_cliente%}
                        <tr>
                           <td class="column"><a href="{% url 'general_usage:lista-objetos' 'interaccion' interaccion.fecha interaccion.pk %}">{{interaccion.fecha}}</a></td>

                           <td>{{interaccion.observaciones}}</td>
                           <td>{{tipo}}</td>
                           <td class="column rigth">                           
                              {% if interaccion.estado != "FINALIZADA"%}

                                 <button title="Crear nota" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalCrearNota" onclick="setUrlModal1('{% url 'general_usage:crear-nota' 'interaccion' interaccion.pk %}', 'action', 'nota')" {{visibilidad}}><i class="bi bi-journal-plus"></i>
                                 </button>
                                 <button title="Añadir archivos" type="button" class="btn btn-disabled btn-secondary" data-bs-toggle="modal" onclick="setUrlModal1('{% url 'general_usage:subir-archivo' 'interaccion' interaccion.pk%}', 'action', 'subir')"data-bs-target="#modalSubirArchivos"{{visibilidad}}><i class="bi bi-file-earmark-plus"></i>
                                 </button>

                                 {% if tipo == "Visita" %}

                                    <button title="Reprogramar" type="button" class="btn btn-warning" data-bs-toggle="modal" onclick="setUrlModal1('{% url 'clientes:reprogramar-visita' interaccion.pk %}', 'action', 'reprogramar')"  data-bs-target="#modalReprogramarVisita"><i class="bi bi-calendar4-range"></i></button>

                                    <button title="Finalizar visita" type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#modalFinalizarVisita" onclick="setUrlModal1('{% url 'clientes:finalizar-visita' interaccion.pk %}', 'href', 'link-finalizar')"  {{visibilidad}}><i class="bi bi-check-circle"></i></button>
                                 {% else %}
                                    <button title="No responde/No desea" onclick="location.href='{% url 'clientes:rechazo' cliente.pk interaccion.pk%}'" type="button" class="btn btn-danger" {{visibilidad}} >
                                       <i class="bi bi-telephone-x"></i>
                                    </button>

                                    <button onclick="location.href='{% url 'clientes:finalizar-llamada' interaccion.pk %}'" type="button" class="btn btn-success" title="Acepto servicio" {{visibilidad}}>
                                       <i class="bi bi-telephone-inbound"></i>
                                    </button>

                                    </button>

                                 {% endif %}


                              {% else %}

                              <!-- <a href="{% url 'clientes:editar-visita' interaccion.pk%}" class="btn btn-primary">Editar</a>-->                                                               {% endif %}
                           </td>
                        </tr>
                     {% endfor %}
                  </tbody>
               </table>
            {% endif %}
         </div>
      </div>
   </div>

{% endblock content %}

templates/clientes/eliminar_cliente.html
{% extends 'base.html' %}


{% block content %}
   <form method="POST" action="{% url "clientes:lista-cliente" %}">
      {% csrf_token %}

   </form>
{% endblock content %}

templates/clientes/lista_clientes.html
{% extends 'base.html' %}

{% block content %}
   <div class="row">
      <div class="col-md-12">
         <div class="table-responsive">
            <table class="table table-hover sticky table-striped align-middle" id="clientes-table">
               <thead>               
                     <th class="text-center" col-index=1>Nombre</th>
                     <th class="text-center" col-index=2>Direccion</th>
                     <th class="text-center" col-index=3>Administrador</th>
                     <th class="text-center" col-index=4>Telefono administrador</th>

                     <th class="text-center" col-index=5>Correo administrador</th>
                     <th class="text-center" col-index=6>Frecuencia
                        <select  class="table-filter form-select text-center"   onchange="filter_rows()">
                           <option value="all">Todos</option>
                        </select>
                     </th>
                     <th class="text-center" col-index=7>Fecha de vencimiento
                        <select class="table-filter form-select text-center" onchange="filter_rows()">
                           <option value="all">Todos</option>
                        </select>
                     </th>
                     <th class="text-center" col-index=8>Estado
                        <select class="table-filter form-select text-center" onchange="filter_rows()">
                           <option value="all">Todos</option>
                        </select>
                     </th>
                     <th class="text-center">NIT</th>
               </thead>
               <tbody>             
                  {% for cliente in clientes %}
                     <tr class="text-center">
                        <td><a href="{% url 'clientes:detalles-cliente' cliente.pk %}">{{cliente.nombre_orgnanizacion}}</a></td>
                        <td>{{cliente.direccion}}</td>
                        <td>{{cliente.administrador}}</td>
                        <td>{{cliente.telefono}}</td>
                        <td>{{cliente.correo}}</td>
                        <td>{{cliente.frecuencia_meses}}</td>
                        {% if cliente.fecha_vencimiento == None %}
                           <td>----</td>
                        {% else %}
                           <td>{{cliente.fecha_vencimiento}}</td>
                        {% endif %}
                        <td>{{cliente.estado}}</td>
                        <td>{{cliente.nit}} </td>
                     </tr>
                  {% endfor %}
               </tbody>

            </table>
            <hr/>
            <div class="text-center">
               <a href="{% url 'clientes:crear-cliente' %}" class="btn btn-success align-self-lg-center" role="button">Crear un nuevo cliente</a>
            </div> 

         </div>
      </div>
   </div>

{% endblock content %}

templates/clientes/subir_archivo.html
{% extends 'base.html' %}


{% block content %}
   <a href="{% url 'clientes:lista-cliente' %}">Volver a clientes</a>
   <hr />
   <h1>Subir archivo</h1>
   <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-success">Guardar</button>
   </form>
{% endblock content %}